### ISSUE TITLE
EVE-16 Dodać sortowanie po dacie w Display list of Events

### ISSUE THREAD

**Issue by Albi7331** [akademia-envelo-3/MELO-back#104]
Zadanie:
Poprawić metodę listAllEvents() w klasie EventService, dodać sortowanie po dacie.

Kryteria akceptacji:
- endpoint /v1/events wyświetla tylko i wyłącznie publiczne eventy, z datą większą od systemowej
- wyniki posortowane są po dacie rosnąco

**Comment by Basia413** [comment]
Code Review okay
