### ISSUE TITLE
[BUG-03] Naprawić implementację wyświetlania przyjaznych wiadomości dla błędów

### ISSUE THREAD

**Issue by Albi7331** [akademia-envelo-3/MELO-back#180]
### Zadanie:
- Zidentyfikować i naprawić błąd dotyczący braku wyświetlania przyjaznych wiadomości dla błędów zdefiniowanych w klasie ApplicationExceptionHandler. Błąd zaczął występować po zmergowaniu taska https://github.com/akademia-envelo-3/MELO-back/issues/108
### Kryteria akceptacji:
- Aplikacja wyświetla przyjazne wiadomości dla błędów zdefiniowanych w ww. klasie
- Aplikacja nie wyrzuca nieoczekiwanych błędów

**Comment by iLoveBingo** [comment]
Brak zastrzeżeń. Wspaniała naprawa. Wraz z lokalną społecznością jesteśmy pełni podziwu. Prezydent rozważa wręczenie kluczy do miasta Radom i nadanie honorowego obywatelstwa. Ukłony i pozdrowienia dla całej rodziny.
