### ISSUE TITLE
EVE-14 Zaimplementować funkcjonalność "Create poll"

### ISSUE THREAD

**Issue by przemyslawmroczek** [akademia-envelo-3/MELO-back#54]
**Warunki wstępne:**

- [ ]  Ukonćzony task [EVE-24](https://github.com/akademia-envelo-3/MELO-back/issues/124)
- [ ]  PollService przyjmuje  PollRepository, PollAnswerRepository
- [ ]  [Diagram pomocniczy](https://app.diagrams.net/#G1tlWXAN-YmH3q36eRUlPHq3PNlyLWVDaV) -> ClassDiagram
- [ ]  [Dokument formularzy](https://docs.google.com/document/d/1LQAYiT2Je12DSQuzXZPOhT8BmvZfWDLKD4t_CixxoHg)

**Do wykonania:**
- Zmapuj obiekt Poll na PollDto.
- PollDto przyjmuje  Set<PollAnswersDto>
- Zdefiniuj ciało metody insertNewPoll przyjmujący PollDto  w PollService, który tworzy nowy Poll w bazie danych.
`public PollTemplate insertNewPoll(PollDto)`
- Zdefiniuj ciało metody addPollToEvent w EventController
`public ResponseEntity<PollDto> addPollToEvent(PollDto pollDto);`

**Warunki ukończenia:**
- Ankieta dodawana do Eventu jest poprawnie zwalidowana przed wysłaniem do bazy danych

**Comment by Basia413** [comment]
Dostosować do zmian z taska EVE-24
